---
image: docker:latest

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test

before_script:
  - docker info
  - rm -rf "/var/cache/apk/*"
  - apk -U upgrade && apk update
  - apk add libffi-dev openssl-dev musl-dev libressl-dev build-base make gcc
  - apk add python3 python3-dev py3-pip py3-cryptography

molecule:
  stage: test
  tags:
    - docker
  script:
    - docker -v
    - python3 -V
    - python3 -m pip install ansible ansible-lint
    - python3 -m pip install flake8 molecule yamllint requests
    - python3 -m pip install docker docker-compose
    - python3 -m pip install "molecule[docker]"
    - ansible --version
    - molecule --version
    - molecule test -s default  # single
    - molecule test -s cluster  # cluster and cluster + 1 to test auto-scaling
  except:
    changes:
      - README.md
