---
- name: arbiter | ensure garbd is installed
  dnf:
    name: percona-xtradb-cluster-garbd

- name: arbiter | place gardb config in /etc/sysconfig/garbd
  template:
    src: arbiter.j2
    dest: /etc/sysconfig/garb
    owner: root
    group: root
    mode: 0644
  register: arb_conf
  tags:
    - molecule-idempotence-notest

- name: arbiter | check whether garbd log exists
  stat:
    path: /var/log/garbd.log
  register: garbd_check

- name: arbiter | touch log file
  file:
    path: /var/log/garbd.log
    state: touch
    owner: root
    group: root
    mode: 0774
  when: not garbd_check.stat.exists

- name: arbiter | ensure garb.service.d in systemd directory exists
  file:
    path: /etc/systemd/system/garb.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: arbiter | template garb override file
  template:
    src: garb.j2
    dest: /etc/systemd/system/garb.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  register: override_garbd

- name: arbiter | reload deamons when garbd service file changed
  systemd:
    daemon_reload: true
  when: override_garbd.changed

- name: arbiter | ensure garbd service is started and enabled
  systemd:
    name: garb
    state: started
    enabled: true

- name: arbiter | restart garbd service when config changed
  systemd:
    name: garb
    state: restarted
  when: arb_conf.changed
  tags:
    - molecule-idempotence-notest
