---
- name: backup | ensure backup dir exists
  file:
    path: "{{ percona_backup.dir }}"
    state: directory
    owner: root
    group: root
    mode: '0600'

- name: backup | ensure backup script is set
  template:
    src: backup.sh.j2
    dest: /etc/mysql/backup.sh
    mode: '0700'
    owner: root
    group: root

- name: backup | ensure cron is installed
  dnf:
    name: crontabs

- name: backup | start and enable crond service
  systemd:
    name: crond
    state: started
    enabled: true

- name: backup | ensure cron is set
  cron:
    name: 'mysql backup'
    user: root
    minute: "{{ percona_backup.minute }}"
    hour: "{{ percona_backup.hour }}"
    job: /etc/mysql/backup.sh
