---
- name: databases | set fact to choose host to perform users task
  set_fact:
    host_on_dbs: "{{ item }}"
  loop: "{{ ansible_play_hosts }}"
  when: not arbiter

- name: databases | set fact for other hosts
  set_fact:
    host_on_dbs: false
  when: host_on_users is undefined

- name: databases | ensure user defined databases exist
  mysql_db:
    login_host: ''
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item }}"
    login_user: root
    state: present
  loop: "{{ percona_databases }}"
  when: inventory_hostname == host_on_dbs or host_count == '1'
