---
- name: databases | ensure databases are set
  mysql_db:
    login_host: ''
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item }}"
    state: present
  loop: "{{ percona_databases }}"
  when: (bootstrapper is defined and bootstrapper) or host_count == '1'
