---
- name: users | ensure users are set
  mysql_user:
    login_host: ''
    login_unix_socket: "{{ mysqld.socket }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    encrypted: "{{ item.encrypted }}"
    priv: "{{ item.privs }}"
    host: "{{ item.host }}"
    state: "{{ item.state }}"
    update_password: always
  loop: "{{ percona_users }}"
  changed_when: false
  when: (bootstrapper is defined and bootstrapper) or host_count == '1'
  no_log: "{{ percona_no_log }}"
